Repository GDSC-BSIOTR/Flutter-Widgets, pull requests merged in 2022-09, with the labels that each got.

#20 updated
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#24 Commit by Pratik Gupta - Flutter developer.
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#22 Updated flutter widgets
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#23 updated
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#26 updated
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#27 Added BottomSheet
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#28 Added 33
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#29 Update index.json
  index.json
Labels: Hacktoberfest, hacktober-accepted

#31 Update index.json
  index.json
Labels: Hacktoberfest, hacktober-accepted

#33 Update index.json
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#35 Update
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#36 Update index.json
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted

#37 update info
  index.json
Labels: Hacktoberfest, hacktoberfest-accepted
